# mappings/levels_zones_map.py

FIELD_MAPPING = {
    'notion_to_supabase': {
        'Ticker ID': 'ticker_id',
        'Ticker': 'ticker',
        'Date': 'date',
        'AD3': 'ad3',
        'AD2': 'ad2',
        'AD1': 'ad1',
        'BD1': 'bd1',
        'BD2': 'bd2',
        'BD3': 'bd3',
        'Type': 'type',
        'S6': 's6',
        'S4': 's4',
        'S3': 's3',
        'R3': 'r3',
        'R4': 'r4',
        'R6': 'r6',
        'WS6': 'ws6',
        'WS4': 'ws4',
        'WS3': 'ws3',
        'WR3': 'wr3',
        'WR4': 'wr4',
        'WR6': 'wr6',
        'H4S2 High': 'h4s2_high',
        'H4S2 Low': 'h4s2_low',
        'H4S1 Low': 'h4s1_low',
        'H4S1 High': 'h4s1_high',
        'H4R1 Low': 'h4r1_low',
        'H4R1 High': 'h4r1_high',
        'H4R2 Low': 'h4r2_low',
        'H4R2 High': 'h4r2_high',
        'BHVN2 Low': 'bhvn2_low',
        'BHVN2 High': 'bhvn2_high',
        'AHVN1 Low': 'ahvn1_low',
        'AHVN2 Low': 'ahvn2_low',
        'AHVN1 High': 'ahvn1_high',
        'AHVN2 High': 'ahvn2_high',
        'BHVN1 High': 'bhvn1_high',
        'BHVN1 Low': 'bhvn1_low',
        'Supabase ID': 'supabase_id'
    },
    'supabase_to_notion': {
        'ticker_id': 'Ticker ID',
        'ticker': 'Ticker',
        'date': 'Date',
        'ad3': 'AD3',
        'ad2': 'AD2',
        'ad1': 'AD1',
        'bd1': 'BD1',
        'bd2': 'BD2',
        'bd3': 'BD3',
        'type': 'Type',
        's6': 'S6',
        's4': 'S4',
        's3': 'S3',
        'r3': 'R3',
        'r4': 'R4',
        'r6': 'R6',
        'ws6': 'WS6',
        'ws4': 'WS4',
        'ws3': 'WS3',
        'wr3': 'WR3',
        'wr4': 'WR4',
        'wr6': 'WR6',
        'h4s2_high': 'H4S2 High',
        'h4s2_low': 'H4S2 Low',
        'h4s1_low': 'H4S1 Low',
        'h4s1_high': 'H4S1 High',
        'h4r1_low': 'H4R1 Low',
        'h4r1_high': 'H4R1 High',
        'h4r2_low': 'H4R2 Low',
        'h4r2_high': 'H4R2 High',
        'bhvn2_low': 'BHVN2 Low',
        'bhvn2_high': 'BHVN2 High',
        'ahvn1_low': 'AHVN1 Low',
        'ahvn2_low': 'AHVN2 Low',
        'ahvn1_high': 'AHVN1 High',
        'ahvn2_high': 'AHVN2 High',
        'bhvn1_high': 'BHVN1 High',
        'bhvn1_low': 'BHVN1 Low',
        'created_at': 'Created At',
        'updated_at': 'Updated At',
        'supabase_id': 'Supabase ID'  # Maps Supabase ID to the tracking field
    },
    'id_field': 'supabase_id',
    'field_types': {
        'Ticker': 'title',  # Ticker is the title field in Notion
        'Date': 'date',
        'Type': 'select'  # Assuming Type is a select field
    }
}